#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright 2020 BayLibre, SAS.
# Author: Fabien Parent <fparent@baylibre.com>

import rity

app_description = """
    RITY configuration tool

    This tool is used to check the environment of the host machine.
"""

if __name__ == "__main__":
    app = rity.App(description=app_description)
    app.execute()

    config = rity.Config()
    config.check()
